
package org.onvif.ver10.device.wsdl;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-06-28T16:57:51.495+08:00
 * Generated source version: 2.7.18
 * 
 */
public final class Device_DevicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.onvif.org/ver10/device/wsdl", "DeviceService");

    private Device_DevicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = DeviceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        DeviceService ss = new DeviceService(wsdlURL, SERVICE_NAME);
        Device port = ss.getDevicePort();  
        
        {
        System.out.println("Invoking setRelayOutputSettings...");
        java.lang.String _setRelayOutputSettings_relayOutputToken = "";
        org.onvif.ver10.schema.RelayOutputSettings _setRelayOutputSettings_properties = null;
        port.setRelayOutputSettings(_setRelayOutputSettings_relayOutputToken, _setRelayOutputSettings_properties);


        }
        {
        System.out.println("Invoking setZeroConfiguration...");
        java.lang.String _setZeroConfiguration_interfaceToken = "";
        boolean _setZeroConfiguration_enabled = false;
        port.setZeroConfiguration(_setZeroConfiguration_interfaceToken, _setZeroConfiguration_enabled);


        }
        {
        System.out.println("Invoking setSystemFactoryDefault...");
        org.onvif.ver10.schema.FactoryDefaultType _setSystemFactoryDefault_factoryDefault = null;
        port.setSystemFactoryDefault(_setSystemFactoryDefault_factoryDefault);


        }
        {
        System.out.println("Invoking getNTP...");
        org.onvif.ver10.schema.NTPInformation _getNTP__return = port.getNTP();
        System.out.println("getNTP.result=" + _getNTP__return);


        }
        {
        System.out.println("Invoking getCACertificates...");
        java.util.List<org.onvif.ver10.schema.Certificate> _getCACertificates__return = port.getCACertificates();
        System.out.println("getCACertificates.result=" + _getCACertificates__return);


        }
        {
        System.out.println("Invoking getClientCertificateMode...");
        boolean _getClientCertificateMode__return = port.getClientCertificateMode();
        System.out.println("getClientCertificateMode.result=" + _getClientCertificateMode__return);


        }
        {
        System.out.println("Invoking getDynamicDNS...");
        org.onvif.ver10.schema.DynamicDNSInformation _getDynamicDNS__return = port.getDynamicDNS();
        System.out.println("getDynamicDNS.result=" + _getDynamicDNS__return);


        }
        {
        System.out.println("Invoking setNetworkDefaultGateway...");
        java.util.List<java.lang.String> _setNetworkDefaultGateway_iPv4Address = null;
        java.util.List<java.lang.String> _setNetworkDefaultGateway_iPv6Address = null;
        port.setNetworkDefaultGateway(_setNetworkDefaultGateway_iPv4Address, _setNetworkDefaultGateway_iPv6Address);


        }
        {
        System.out.println("Invoking getCertificatesStatus...");
        java.util.List<org.onvif.ver10.schema.CertificateStatus> _getCertificatesStatus__return = port.getCertificatesStatus();
        System.out.println("getCertificatesStatus.result=" + _getCertificatesStatus__return);


        }
        {
        System.out.println("Invoking sendAuxiliaryCommand...");
        java.lang.String _sendAuxiliaryCommand_auxiliaryCommand = "";
        java.lang.String _sendAuxiliaryCommand__return = port.sendAuxiliaryCommand(_sendAuxiliaryCommand_auxiliaryCommand);
        System.out.println("sendAuxiliaryCommand.result=" + _sendAuxiliaryCommand__return);


        }
        {
        System.out.println("Invoking getCapabilities...");
        java.util.List<org.onvif.ver10.schema.CapabilityCategory> _getCapabilities_category = null;
        org.onvif.ver10.schema.Capabilities _getCapabilities__return = port.getCapabilities(_getCapabilities_category);
        System.out.println("getCapabilities.result=" + _getCapabilities__return);


        }
        {
        System.out.println("Invoking deleteStorageConfiguration...");
        java.lang.String _deleteStorageConfiguration_token = "";
        port.deleteStorageConfiguration(_deleteStorageConfiguration_token);


        }
        {
        System.out.println("Invoking setNetworkProtocols...");
        java.util.List<org.onvif.ver10.schema.NetworkProtocol> _setNetworkProtocols_networkProtocols = null;
        port.setNetworkProtocols(_setNetworkProtocols_networkProtocols);


        }
        {
        System.out.println("Invoking setStorageConfiguration...");
        org.onvif.ver10.device.wsdl.StorageConfiguration _setStorageConfiguration_storageConfiguration = null;
        port.setStorageConfiguration(_setStorageConfiguration_storageConfiguration);


        }
        {
        System.out.println("Invoking getNetworkDefaultGateway...");
        org.onvif.ver10.schema.NetworkGateway _getNetworkDefaultGateway__return = port.getNetworkDefaultGateway();
        System.out.println("getNetworkDefaultGateway.result=" + _getNetworkDefaultGateway__return);


        }
        {
        System.out.println("Invoking deleteCertificates...");
        java.util.List<java.lang.String> _deleteCertificates_certificateID = null;
        port.deleteCertificates(_deleteCertificates_certificateID);


        }
        {
        System.out.println("Invoking setDPAddresses...");
        java.util.List<org.onvif.ver10.schema.NetworkHost> _setDPAddresses_dpAddress = null;
        port.setDPAddresses(_setDPAddresses_dpAddress);


        }
        {
        System.out.println("Invoking getIPAddressFilter...");
        org.onvif.ver10.schema.IPAddressFilter _getIPAddressFilter__return = port.getIPAddressFilter();
        System.out.println("getIPAddressFilter.result=" + _getIPAddressFilter__return);


        }
        {
        System.out.println("Invoking setDNS...");
        boolean _setDNS_fromDHCP = false;
        java.util.List<java.lang.String> _setDNS_searchDomain = null;
        java.util.List<org.onvif.ver10.schema.IPAddress> _setDNS_dnsManual = null;
        port.setDNS(_setDNS_fromDHCP, _setDNS_searchDomain, _setDNS_dnsManual);


        }
        {
        System.out.println("Invoking setClientCertificateMode...");
        boolean _setClientCertificateMode_enabled = false;
        port.setClientCertificateMode(_setClientCertificateMode_enabled);


        }
        {
        System.out.println("Invoking removeScopes...");
        java.util.List<java.lang.String> _removeScopes_scopeItemVal = null;
        javax.xml.ws.Holder<java.util.List<java.lang.String>> _removeScopes_scopeItem = new javax.xml.ws.Holder<java.util.List<java.lang.String>>(_removeScopes_scopeItemVal);
        port.removeScopes(_removeScopes_scopeItem);

        System.out.println("removeScopes._removeScopes_scopeItem=" + _removeScopes_scopeItem.value);

        }
        {
        System.out.println("Invoking createStorageConfiguration...");
        org.onvif.ver10.device.wsdl.StorageConfigurationData _createStorageConfiguration_storageConfiguration = null;
        java.lang.String _createStorageConfiguration__return = port.createStorageConfiguration(_createStorageConfiguration_storageConfiguration);
        System.out.println("createStorageConfiguration.result=" + _createStorageConfiguration__return);


        }
        {
        System.out.println("Invoking getServices...");
        boolean _getServices_includeCapability = false;
        java.util.List<org.onvif.ver10.device.wsdl.Service> _getServices__return = port.getServices(_getServices_includeCapability);
        System.out.println("getServices.result=" + _getServices__return);


        }
        {
        System.out.println("Invoking scanAvailableDot11Networks...");
        java.lang.String _scanAvailableDot11Networks_interfaceToken = "";
        java.util.List<org.onvif.ver10.schema.Dot11AvailableNetworks> _scanAvailableDot11Networks__return = port.scanAvailableDot11Networks(_scanAvailableDot11Networks_interfaceToken);
        System.out.println("scanAvailableDot11Networks.result=" + _scanAvailableDot11Networks__return);


        }
        {
        System.out.println("Invoking setIPAddressFilter...");
        org.onvif.ver10.schema.IPAddressFilter _setIPAddressFilter_ipAddressFilter = null;
        port.setIPAddressFilter(_setIPAddressFilter_ipAddressFilter);


        }
        {
        System.out.println("Invoking getSystemDateAndTime...");
        org.onvif.ver10.schema.SystemDateTime _getSystemDateAndTime__return = port.getSystemDateAndTime();
        System.out.println("getSystemDateAndTime.result=" + _getSystemDateAndTime__return);


        }
        {
        System.out.println("Invoking getDot11Capabilities...");
        org.onvif.ver10.device.wsdl.GetDot11Capabilities _getDot11Capabilities_parameters = null;
        org.onvif.ver10.device.wsdl.GetDot11CapabilitiesResponse _getDot11Capabilities__return = port.getDot11Capabilities(_getDot11Capabilities_parameters);
        System.out.println("getDot11Capabilities.result=" + _getDot11Capabilities__return);


        }
        {
        System.out.println("Invoking getSystemUris...");
        javax.xml.ws.Holder<org.onvif.ver10.schema.SystemLogUriList> _getSystemUris_systemLogUris = new javax.xml.ws.Holder<org.onvif.ver10.schema.SystemLogUriList>();
        javax.xml.ws.Holder<java.lang.String> _getSystemUris_supportInfoUri = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _getSystemUris_systemBackupUri = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<org.onvif.ver10.device.wsdl.GetSystemUrisResponse.Extension> _getSystemUris_extension = new javax.xml.ws.Holder<org.onvif.ver10.device.wsdl.GetSystemUrisResponse.Extension>();
        port.getSystemUris(_getSystemUris_systemLogUris, _getSystemUris_supportInfoUri, _getSystemUris_systemBackupUri, _getSystemUris_extension);

        System.out.println("getSystemUris._getSystemUris_systemLogUris=" + _getSystemUris_systemLogUris.value);
        System.out.println("getSystemUris._getSystemUris_supportInfoUri=" + _getSystemUris_supportInfoUri.value);
        System.out.println("getSystemUris._getSystemUris_systemBackupUri=" + _getSystemUris_systemBackupUri.value);
        System.out.println("getSystemUris._getSystemUris_extension=" + _getSystemUris_extension.value);

        }
        {
        System.out.println("Invoking startSystemRestore...");
        javax.xml.ws.Holder<java.lang.String> _startSystemRestore_uploadUri = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<javax.xml.datatype.Duration> _startSystemRestore_expectedDownTime = new javax.xml.ws.Holder<javax.xml.datatype.Duration>();
        port.startSystemRestore(_startSystemRestore_uploadUri, _startSystemRestore_expectedDownTime);

        System.out.println("startSystemRestore._startSystemRestore_uploadUri=" + _startSystemRestore_uploadUri.value);
        System.out.println("startSystemRestore._startSystemRestore_expectedDownTime=" + _startSystemRestore_expectedDownTime.value);

        }
        {
        System.out.println("Invoking createCertificate...");
        java.lang.String _createCertificate_certificateID = "";
        java.lang.String _createCertificate_subject = "";
        javax.xml.datatype.XMLGregorianCalendar _createCertificate_validNotBefore = null;
        javax.xml.datatype.XMLGregorianCalendar _createCertificate_validNotAfter = null;
        org.onvif.ver10.schema.Certificate _createCertificate__return = port.createCertificate(_createCertificate_certificateID, _createCertificate_subject, _createCertificate_validNotBefore, _createCertificate_validNotAfter);
        System.out.println("createCertificate.result=" + _createCertificate__return);


        }
        {
        System.out.println("Invoking getHostname...");
        org.onvif.ver10.schema.HostnameInformation _getHostname__return = port.getHostname();
        System.out.println("getHostname.result=" + _getHostname__return);


        }
        {
        System.out.println("Invoking setRelayOutputState...");
        java.lang.String _setRelayOutputState_relayOutputToken = "";
        org.onvif.ver10.schema.RelayLogicalState _setRelayOutputState_logicalState = null;
        port.setRelayOutputState(_setRelayOutputState_relayOutputToken, _setRelayOutputState_logicalState);


        }
        {
        System.out.println("Invoking getSystemLog...");
        org.onvif.ver10.schema.SystemLogType _getSystemLog_logType = null;
        org.onvif.ver10.schema.SystemLog _getSystemLog__return = port.getSystemLog(_getSystemLog_logType);
        System.out.println("getSystemLog.result=" + _getSystemLog__return);


        }
        {
        System.out.println("Invoking getCertificates...");
        java.util.List<org.onvif.ver10.schema.Certificate> _getCertificates__return = port.getCertificates();
        System.out.println("getCertificates.result=" + _getCertificates__return);


        }
        {
        System.out.println("Invoking setDiscoveryMode...");
        org.onvif.ver10.schema.DiscoveryMode _setDiscoveryMode_discoveryMode = null;
        port.setDiscoveryMode(_setDiscoveryMode_discoveryMode);


        }
        {
        System.out.println("Invoking setDynamicDNS...");
        org.onvif.ver10.schema.DynamicDNSType _setDynamicDNS_type = null;
        java.lang.String _setDynamicDNS_name = "";
        javax.xml.datatype.Duration _setDynamicDNS_ttl = null;
        port.setDynamicDNS(_setDynamicDNS_type, _setDynamicDNS_name, _setDynamicDNS_ttl);


        }
        {
        System.out.println("Invoking getRemoteDiscoveryMode...");
        org.onvif.ver10.schema.DiscoveryMode _getRemoteDiscoveryMode__return = port.getRemoteDiscoveryMode();
        System.out.println("getRemoteDiscoveryMode.result=" + _getRemoteDiscoveryMode__return);


        }
        {
        System.out.println("Invoking getDNS...");
        org.onvif.ver10.schema.DNSInformation _getDNS__return = port.getDNS();
        System.out.println("getDNS.result=" + _getDNS__return);


        }
        {
        System.out.println("Invoking loadCertificates...");
        java.util.List<org.onvif.ver10.schema.Certificate> _loadCertificates_nvtCertificate = null;
        port.loadCertificates(_loadCertificates_nvtCertificate);


        }
        {
        System.out.println("Invoking setUser...");
        java.util.List<org.onvif.ver10.schema.User> _setUser_user = null;
        port.setUser(_setUser_user);


        }
        {
        System.out.println("Invoking setNTP...");
        boolean _setNTP_fromDHCP = false;
        java.util.List<org.onvif.ver10.schema.NetworkHost> _setNTP_ntpManual = null;
        port.setNTP(_setNTP_fromDHCP, _setNTP_ntpManual);


        }
        {
        System.out.println("Invoking startFirmwareUpgrade...");
        javax.xml.ws.Holder<java.lang.String> _startFirmwareUpgrade_uploadUri = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<javax.xml.datatype.Duration> _startFirmwareUpgrade_uploadDelay = new javax.xml.ws.Holder<javax.xml.datatype.Duration>();
        javax.xml.ws.Holder<javax.xml.datatype.Duration> _startFirmwareUpgrade_expectedDownTime = new javax.xml.ws.Holder<javax.xml.datatype.Duration>();
        port.startFirmwareUpgrade(_startFirmwareUpgrade_uploadUri, _startFirmwareUpgrade_uploadDelay, _startFirmwareUpgrade_expectedDownTime);

        System.out.println("startFirmwareUpgrade._startFirmwareUpgrade_uploadUri=" + _startFirmwareUpgrade_uploadUri.value);
        System.out.println("startFirmwareUpgrade._startFirmwareUpgrade_uploadDelay=" + _startFirmwareUpgrade_uploadDelay.value);
        System.out.println("startFirmwareUpgrade._startFirmwareUpgrade_expectedDownTime=" + _startFirmwareUpgrade_expectedDownTime.value);

        }
        {
        System.out.println("Invoking getEndpointReference...");
        org.onvif.ver10.device.wsdl.GetEndpointReference _getEndpointReference_parameters = null;
        org.onvif.ver10.device.wsdl.GetEndpointReferenceResponse _getEndpointReference__return = port.getEndpointReference(_getEndpointReference_parameters);
        System.out.println("getEndpointReference.result=" + _getEndpointReference__return);


        }
        {
        System.out.println("Invoking setNetworkInterfaces...");
        java.lang.String _setNetworkInterfaces_interfaceToken = "";
        org.onvif.ver10.schema.NetworkInterfaceSetConfiguration _setNetworkInterfaces_networkInterface = null;
        boolean _setNetworkInterfaces__return = port.setNetworkInterfaces(_setNetworkInterfaces_interfaceToken, _setNetworkInterfaces_networkInterface);
        System.out.println("setNetworkInterfaces.result=" + _setNetworkInterfaces__return);


        }
        {
        System.out.println("Invoking setHostnameFromDHCP...");
        boolean _setHostnameFromDHCP_fromDHCP = false;
        boolean _setHostnameFromDHCP__return = port.setHostnameFromDHCP(_setHostnameFromDHCP_fromDHCP);
        System.out.println("setHostnameFromDHCP.result=" + _setHostnameFromDHCP__return);


        }
        {
        System.out.println("Invoking setRemoteUser...");
        org.onvif.ver10.schema.RemoteUser _setRemoteUser_remoteUser = null;
        port.setRemoteUser(_setRemoteUser_remoteUser);


        }
        {
        System.out.println("Invoking addIPAddressFilter...");
        org.onvif.ver10.schema.IPAddressFilter _addIPAddressFilter_ipAddressFilter = null;
        port.addIPAddressFilter(_addIPAddressFilter_ipAddressFilter);


        }
        {
        System.out.println("Invoking deleteUsers...");
        java.util.List<java.lang.String> _deleteUsers_username = null;
        port.deleteUsers(_deleteUsers_username);


        }
        {
        System.out.println("Invoking getCertificateInformation...");
        java.lang.String _getCertificateInformation_certificateID = "";
        org.onvif.ver10.schema.CertificateInformation _getCertificateInformation__return = port.getCertificateInformation(_getCertificateInformation_certificateID);
        System.out.println("getCertificateInformation.result=" + _getCertificateInformation__return);


        }
        {
        System.out.println("Invoking getWsdlUrl...");
        java.lang.String _getWsdlUrl__return = port.getWsdlUrl();
        System.out.println("getWsdlUrl.result=" + _getWsdlUrl__return);


        }
        {
        System.out.println("Invoking getStorageConfiguration...");
        java.lang.String _getStorageConfiguration_token = "";
        org.onvif.ver10.device.wsdl.StorageConfiguration _getStorageConfiguration__return = port.getStorageConfiguration(_getStorageConfiguration_token);
        System.out.println("getStorageConfiguration.result=" + _getStorageConfiguration__return);


        }
        {
        System.out.println("Invoking getRelayOutputs...");
        java.util.List<org.onvif.ver10.schema.RelayOutput> _getRelayOutputs__return = port.getRelayOutputs();
        System.out.println("getRelayOutputs.result=" + _getRelayOutputs__return);


        }
        {
        System.out.println("Invoking getDiscoveryMode...");
        org.onvif.ver10.schema.DiscoveryMode _getDiscoveryMode__return = port.getDiscoveryMode();
        System.out.println("getDiscoveryMode.result=" + _getDiscoveryMode__return);


        }
        {
        System.out.println("Invoking setDot1XConfiguration...");
        org.onvif.ver10.schema.Dot1XConfiguration _setDot1XConfiguration_dot1XConfiguration = null;
        port.setDot1XConfiguration(_setDot1XConfiguration_dot1XConfiguration);


        }
        {
        System.out.println("Invoking getServiceCapabilities...");
        org.onvif.ver10.device.wsdl.DeviceServiceCapabilities _getServiceCapabilities__return = port.getServiceCapabilities();
        System.out.println("getServiceCapabilities.result=" + _getServiceCapabilities__return);


        }
        {
        System.out.println("Invoking setSystemDateAndTime...");
        org.onvif.ver10.schema.SetDateTimeType _setSystemDateAndTime_dateTimeType = null;
        boolean _setSystemDateAndTime_daylightSavings = false;
        org.onvif.ver10.schema.TimeZone _setSystemDateAndTime_timeZone = null;
        org.onvif.ver10.schema.DateTime _setSystemDateAndTime_utcDateTime = null;
        port.setSystemDateAndTime(_setSystemDateAndTime_dateTimeType, _setSystemDateAndTime_daylightSavings, _setSystemDateAndTime_timeZone, _setSystemDateAndTime_utcDateTime);


        }
        {
        System.out.println("Invoking setAccessPolicy...");
        org.onvif.ver10.schema.BinaryData _setAccessPolicy_policyFile = null;
        port.setAccessPolicy(_setAccessPolicy_policyFile);


        }
        {
        System.out.println("Invoking getSystemSupportInformation...");
        org.onvif.ver10.schema.SupportInformation _getSystemSupportInformation__return = port.getSystemSupportInformation();
        System.out.println("getSystemSupportInformation.result=" + _getSystemSupportInformation__return);


        }
        {
        System.out.println("Invoking setScopes...");
        java.util.List<java.lang.String> _setScopes_scopes = null;
        port.setScopes(_setScopes_scopes);


        }
        {
        System.out.println("Invoking getDot1XConfiguration...");
        java.lang.String _getDot1XConfiguration_dot1XConfigurationToken = "";
        org.onvif.ver10.schema.Dot1XConfiguration _getDot1XConfiguration__return = port.getDot1XConfiguration(_getDot1XConfiguration_dot1XConfigurationToken);
        System.out.println("getDot1XConfiguration.result=" + _getDot1XConfiguration__return);


        }
        {
        System.out.println("Invoking getSystemBackup...");
        java.util.List<org.onvif.ver10.schema.BackupFile> _getSystemBackup__return = port.getSystemBackup();
        System.out.println("getSystemBackup.result=" + _getSystemBackup__return);


        }
        {
        System.out.println("Invoking getNetworkInterfaces...");
        java.util.List<org.onvif.ver10.schema.NetworkInterface> _getNetworkInterfaces__return = port.getNetworkInterfaces();
        System.out.println("getNetworkInterfaces.result=" + _getNetworkInterfaces__return);


        }
        {
        System.out.println("Invoking deleteDot1XConfiguration...");
        java.util.List<java.lang.String> _deleteDot1XConfiguration_dot1XConfigurationToken = null;
        port.deleteDot1XConfiguration(_deleteDot1XConfiguration_dot1XConfigurationToken);


        }
        {
        System.out.println("Invoking getAccessPolicy...");
        org.onvif.ver10.schema.BinaryData _getAccessPolicy__return = port.getAccessPolicy();
        System.out.println("getAccessPolicy.result=" + _getAccessPolicy__return);


        }
        {
        System.out.println("Invoking setCertificatesStatus...");
        java.util.List<org.onvif.ver10.schema.CertificateStatus> _setCertificatesStatus_certificateStatus = null;
        port.setCertificatesStatus(_setCertificatesStatus_certificateStatus);


        }
        {
        System.out.println("Invoking getDPAddresses...");
        java.util.List<org.onvif.ver10.schema.NetworkHost> _getDPAddresses__return = port.getDPAddresses();
        System.out.println("getDPAddresses.result=" + _getDPAddresses__return);


        }
        {
        System.out.println("Invoking getZeroConfiguration...");
        org.onvif.ver10.schema.NetworkZeroConfiguration _getZeroConfiguration__return = port.getZeroConfiguration();
        System.out.println("getZeroConfiguration.result=" + _getZeroConfiguration__return);


        }
        {
        System.out.println("Invoking createUsers...");
        java.util.List<org.onvif.ver10.schema.User> _createUsers_user = null;
        port.createUsers(_createUsers_user);


        }
        {
        System.out.println("Invoking addScopes...");
        java.util.List<java.lang.String> _addScopes_scopeItem = null;
        port.addScopes(_addScopes_scopeItem);


        }
        {
        System.out.println("Invoking systemReboot...");
        java.lang.String _systemReboot__return = port.systemReboot();
        System.out.println("systemReboot.result=" + _systemReboot__return);


        }
        {
        System.out.println("Invoking getDeviceInformation...");
        javax.xml.ws.Holder<java.lang.String> _getDeviceInformation_manufacturer = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _getDeviceInformation_model = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _getDeviceInformation_firmwareVersion = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _getDeviceInformation_serialNumber = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _getDeviceInformation_hardwareId = new javax.xml.ws.Holder<java.lang.String>();
        port.getDeviceInformation(_getDeviceInformation_manufacturer, _getDeviceInformation_model, _getDeviceInformation_firmwareVersion, _getDeviceInformation_serialNumber, _getDeviceInformation_hardwareId);

        System.out.println("getDeviceInformation._getDeviceInformation_manufacturer=" + _getDeviceInformation_manufacturer.value);
        System.out.println("getDeviceInformation._getDeviceInformation_model=" + _getDeviceInformation_model.value);
        System.out.println("getDeviceInformation._getDeviceInformation_firmwareVersion=" + _getDeviceInformation_firmwareVersion.value);
        System.out.println("getDeviceInformation._getDeviceInformation_serialNumber=" + _getDeviceInformation_serialNumber.value);
        System.out.println("getDeviceInformation._getDeviceInformation_hardwareId=" + _getDeviceInformation_hardwareId.value);

        }
        {
        System.out.println("Invoking getRemoteUser...");
        org.onvif.ver10.schema.RemoteUser _getRemoteUser__return = port.getRemoteUser();
        System.out.println("getRemoteUser.result=" + _getRemoteUser__return);


        }
        {
        System.out.println("Invoking createDot1XConfiguration...");
        org.onvif.ver10.schema.Dot1XConfiguration _createDot1XConfiguration_dot1XConfiguration = null;
        port.createDot1XConfiguration(_createDot1XConfiguration_dot1XConfiguration);


        }
        {
        System.out.println("Invoking loadCACertificates...");
        java.util.List<org.onvif.ver10.schema.Certificate> _loadCACertificates_caCertificate = null;
        port.loadCACertificates(_loadCACertificates_caCertificate);


        }
        {
        System.out.println("Invoking setHostname...");
        java.lang.String _setHostname_name = "";
        port.setHostname(_setHostname_name);


        }
        {
        System.out.println("Invoking removeIPAddressFilter...");
        org.onvif.ver10.schema.IPAddressFilter _removeIPAddressFilter_ipAddressFilter = null;
        port.removeIPAddressFilter(_removeIPAddressFilter_ipAddressFilter);


        }
        {
        System.out.println("Invoking getUsers...");
        java.util.List<org.onvif.ver10.schema.User> _getUsers__return = port.getUsers();
        System.out.println("getUsers.result=" + _getUsers__return);


        }
        {
        System.out.println("Invoking getStorageConfigurations...");
        java.util.List<org.onvif.ver10.device.wsdl.StorageConfiguration> _getStorageConfigurations__return = port.getStorageConfigurations();
        System.out.println("getStorageConfigurations.result=" + _getStorageConfigurations__return);


        }
        {
        System.out.println("Invoking setRemoteDiscoveryMode...");
        org.onvif.ver10.schema.DiscoveryMode _setRemoteDiscoveryMode_remoteDiscoveryMode = null;
        port.setRemoteDiscoveryMode(_setRemoteDiscoveryMode_remoteDiscoveryMode);


        }
        {
        System.out.println("Invoking getNetworkProtocols...");
        java.util.List<org.onvif.ver10.schema.NetworkProtocol> _getNetworkProtocols__return = port.getNetworkProtocols();
        System.out.println("getNetworkProtocols.result=" + _getNetworkProtocols__return);


        }
        {
        System.out.println("Invoking getScopes...");
        java.util.List<org.onvif.ver10.schema.Scope> _getScopes__return = port.getScopes();
        System.out.println("getScopes.result=" + _getScopes__return);


        }
        {
        System.out.println("Invoking loadCertificateWithPrivateKey...");
        java.util.List<org.onvif.ver10.schema.CertificateWithPrivateKey> _loadCertificateWithPrivateKey_certificateWithPrivateKey = null;
        port.loadCertificateWithPrivateKey(_loadCertificateWithPrivateKey_certificateWithPrivateKey);


        }
        {
        System.out.println("Invoking upgradeSystemFirmware...");
        org.onvif.ver10.schema.AttachmentData _upgradeSystemFirmware_firmware = null;
        java.lang.String _upgradeSystemFirmware__return = port.upgradeSystemFirmware(_upgradeSystemFirmware_firmware);
        System.out.println("upgradeSystemFirmware.result=" + _upgradeSystemFirmware__return);


        }
        {
        System.out.println("Invoking getDot11Status...");
        java.lang.String _getDot11Status_interfaceToken = "";
        org.onvif.ver10.schema.Dot11Status _getDot11Status__return = port.getDot11Status(_getDot11Status_interfaceToken);
        System.out.println("getDot11Status.result=" + _getDot11Status__return);


        }
        {
        System.out.println("Invoking getPkcs10Request...");
        java.lang.String _getPkcs10Request_certificateID = "";
        java.lang.String _getPkcs10Request_subject = "";
        org.onvif.ver10.schema.BinaryData _getPkcs10Request_attributes = null;
        org.onvif.ver10.schema.BinaryData _getPkcs10Request__return = port.getPkcs10Request(_getPkcs10Request_certificateID, _getPkcs10Request_subject, _getPkcs10Request_attributes);
        System.out.println("getPkcs10Request.result=" + _getPkcs10Request__return);


        }
        {
        System.out.println("Invoking getDot1XConfigurations...");
        java.util.List<org.onvif.ver10.schema.Dot1XConfiguration> _getDot1XConfigurations__return = port.getDot1XConfigurations();
        System.out.println("getDot1XConfigurations.result=" + _getDot1XConfigurations__return);


        }
        {
        System.out.println("Invoking restoreSystem...");
        java.util.List<org.onvif.ver10.schema.BackupFile> _restoreSystem_backupFiles = null;
        port.restoreSystem(_restoreSystem_backupFiles);


        }

        System.exit(0);
    }

}
