
package org.onvif.ver10.device.wsdl;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-06-28T16:57:51.759+08:00
 * Generated source version: 2.7.18
 * 
 */
 
public class Device_DevicePort_Server{

    protected Device_DevicePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new DeviceImpl();
        String address = "http://172.16.2.32/onvif/device_service";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new Device_DevicePort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
