
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.onvif.ver10.device.wsdl;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-06-28T16:57:51.588+08:00
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "DeviceService",
                      portName = "DevicePort",
                      targetNamespace = "http://www.onvif.org/ver10/device/wsdl",
                      wsdlLocation = "file:/D:/OPENCVR/javaonvif/wsdls/devicemgmt_1.wsdl",
                      endpointInterface = "org.onvif.ver10.device.wsdl.Device")
                      
public class DeviceImpl implements Device {

    private static final Logger LOG = Logger.getLogger(DeviceImpl.class.getName());

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#setRelayOutputSettings(java.lang.String  relayOutputToken ,)org.onvif.ver10.schema.RelayOutputSettings  properties )*
     */
    public void setRelayOutputSettings(java.lang.String relayOutputToken,org.onvif.ver10.schema.RelayOutputSettings properties) { 
        LOG.info("Executing operation setRelayOutputSettings");
        System.out.println(relayOutputToken);
        System.out.println(properties);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#setZeroConfiguration(java.lang.String  interfaceToken ,)boolean  enabled )*
     */
    public void setZeroConfiguration(java.lang.String interfaceToken,boolean enabled) { 
        LOG.info("Executing operation setZeroConfiguration");
        System.out.println(interfaceToken);
        System.out.println(enabled);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#setSystemFactoryDefault(org.onvif.ver10.schema.FactoryDefaultType  factoryDefault )*
     */
    public void setSystemFactoryDefault(org.onvif.ver10.schema.FactoryDefaultType factoryDefault) { 
        LOG.info("Executing operation setSystemFactoryDefault");
        System.out.println(factoryDefault);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#getNTP(*
     */
    public org.onvif.ver10.schema.NTPInformation getNTP() { 
        LOG.info("Executing operation getNTP");
        try {
            org.onvif.ver10.schema.NTPInformation _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#getCACertificates(*
     */
    public java.util.List<org.onvif.ver10.schema.Certificate> getCACertificates() { 
        LOG.info("Executing operation getCACertificates");
        try {
            java.util.List<org.onvif.ver10.schema.Certificate> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#getClientCertificateMode(*
     */
    public boolean getClientCertificateMode() { 
        LOG.info("Executing operation getClientCertificateMode");
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#getDynamicDNS(*
     */
    public org.onvif.ver10.schema.DynamicDNSInformation getDynamicDNS() { 
        LOG.info("Executing operation getDynamicDNS");
        try {
            org.onvif.ver10.schema.DynamicDNSInformation _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#setNetworkDefaultGateway(java.util.List<java.lang.String>  iPv4Address ,)java.util.List<java.lang.String>  iPv6Address )*
     */
    public void setNetworkDefaultGateway(java.util.List<java.lang.String> iPv4Address,java.util.List<java.lang.String> iPv6Address) { 
        LOG.info("Executing operation setNetworkDefaultGateway");
        System.out.println(iPv4Address);
        System.out.println(iPv6Address);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#getCertificatesStatus(*
     */
    public java.util.List<org.onvif.ver10.schema.CertificateStatus> getCertificatesStatus() { 
        LOG.info("Executing operation getCertificatesStatus");
        try {
            java.util.List<org.onvif.ver10.schema.CertificateStatus> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#sendAuxiliaryCommand(java.lang.String  auxiliaryCommand )*
     */
    public java.lang.String sendAuxiliaryCommand(java.lang.String auxiliaryCommand) { 
        LOG.info("Executing operation sendAuxiliaryCommand");
        System.out.println(auxiliaryCommand);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#getCapabilities(java.util.List<org.onvif.ver10.schema.CapabilityCategory>  category )*
     */
    public org.onvif.ver10.schema.Capabilities getCapabilities(java.util.List<org.onvif.ver10.schema.CapabilityCategory> category) { 
        LOG.info("Executing operation getCapabilities");
        System.out.println(category);
        try {
            org.onvif.ver10.schema.Capabilities _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#deleteStorageConfiguration(java.lang.String  token )*
     */
    public void deleteStorageConfiguration(java.lang.String token) { 
        LOG.info("Executing operation deleteStorageConfiguration");
        System.out.println(token);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#setNetworkProtocols(java.util.List<org.onvif.ver10.schema.NetworkProtocol>  networkProtocols )*
     */
    public void setNetworkProtocols(java.util.List<org.onvif.ver10.schema.NetworkProtocol> networkProtocols) { 
        LOG.info("Executing operation setNetworkProtocols");
        System.out.println(networkProtocols);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#setStorageConfiguration(org.onvif.ver10.device.wsdl.StorageConfiguration  storageConfiguration )*
     */
    public void setStorageConfiguration(org.onvif.ver10.device.wsdl.StorageConfiguration storageConfiguration) { 
        LOG.info("Executing operation setStorageConfiguration");
        System.out.println(storageConfiguration);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#getNetworkDefaultGateway(*
     */
    public org.onvif.ver10.schema.NetworkGateway getNetworkDefaultGateway() { 
        LOG.info("Executing operation getNetworkDefaultGateway");
        try {
            org.onvif.ver10.schema.NetworkGateway _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#deleteCertificates(java.util.List<java.lang.String>  certificateID )*
     */
    public void deleteCertificates(java.util.List<java.lang.String> certificateID) { 
        LOG.info("Executing operation deleteCertificates");
        System.out.println(certificateID);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#setDPAddresses(java.util.List<org.onvif.ver10.schema.NetworkHost>  dpAddress )*
     */
    public void setDPAddresses(java.util.List<org.onvif.ver10.schema.NetworkHost> dpAddress) { 
        LOG.info("Executing operation setDPAddresses");
        System.out.println(dpAddress);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#getIPAddressFilter(*
     */
    public org.onvif.ver10.schema.IPAddressFilter getIPAddressFilter() { 
        LOG.info("Executing operation getIPAddressFilter");
        try {
            org.onvif.ver10.schema.IPAddressFilter _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#setDNS(boolean  fromDHCP ,)java.util.List<java.lang.String>  searchDomain ,)java.util.List<org.onvif.ver10.schema.IPAddress>  dnsManual )*
     */
    public void setDNS(boolean fromDHCP,java.util.List<java.lang.String> searchDomain,java.util.List<org.onvif.ver10.schema.IPAddress> dnsManual) { 
        LOG.info("Executing operation setDNS");
        System.out.println(fromDHCP);
        System.out.println(searchDomain);
        System.out.println(dnsManual);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#setClientCertificateMode(boolean  enabled )*
     */
    public void setClientCertificateMode(boolean enabled) { 
        LOG.info("Executing operation setClientCertificateMode");
        System.out.println(enabled);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#removeScopes(java.util.List<java.lang.String>  scopeItem )*
     */
    public void removeScopes(javax.xml.ws.Holder<java.util.List<java.lang.String>> scopeItem) { 
        LOG.info("Executing operation removeScopes");
        System.out.println(scopeItem.value);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#createStorageConfiguration(org.onvif.ver10.device.wsdl.StorageConfigurationData  storageConfiguration )*
     */
    public java.lang.String createStorageConfiguration(org.onvif.ver10.device.wsdl.StorageConfigurationData storageConfiguration) { 
        LOG.info("Executing operation createStorageConfiguration");
        System.out.println(storageConfiguration);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#getServices(boolean  includeCapability )*
     */
    public java.util.List<org.onvif.ver10.device.wsdl.Service> getServices(boolean includeCapability) { 
        LOG.info("Executing operation getServices");
        System.out.println(includeCapability);
        try {
            java.util.List<org.onvif.ver10.device.wsdl.Service> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#scanAvailableDot11Networks(java.lang.String  interfaceToken )*
     */
    public java.util.List<org.onvif.ver10.schema.Dot11AvailableNetworks> scanAvailableDot11Networks(java.lang.String interfaceToken) { 
        LOG.info("Executing operation scanAvailableDot11Networks");
        System.out.println(interfaceToken);
        try {
            java.util.List<org.onvif.ver10.schema.Dot11AvailableNetworks> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#setIPAddressFilter(org.onvif.ver10.schema.IPAddressFilter  ipAddressFilter )*
     */
    public void setIPAddressFilter(org.onvif.ver10.schema.IPAddressFilter ipAddressFilter) { 
        LOG.info("Executing operation setIPAddressFilter");
        System.out.println(ipAddressFilter);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#getSystemDateAndTime(*
     */
    public org.onvif.ver10.schema.SystemDateTime getSystemDateAndTime() { 
        LOG.info("Executing operation getSystemDateAndTime");
        try {
            org.onvif.ver10.schema.SystemDateTime _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#getDot11Capabilities(org.onvif.ver10.device.wsdl.GetDot11Capabilities  parameters )*
     */
    public org.onvif.ver10.device.wsdl.GetDot11CapabilitiesResponse getDot11Capabilities(GetDot11Capabilities parameters) { 
        LOG.info("Executing operation getDot11Capabilities");
        System.out.println(parameters);
        try {
            org.onvif.ver10.device.wsdl.GetDot11CapabilitiesResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#getSystemUris(org.onvif.ver10.schema.SystemLogUriList  systemLogUris ,)java.lang.String  supportInfoUri ,)java.lang.String  systemBackupUri ,)org.onvif.ver10.device.wsdl.GetSystemUrisResponse.Extension  extension )*
     */
    public void getSystemUris(javax.xml.ws.Holder<org.onvif.ver10.schema.SystemLogUriList> systemLogUris,javax.xml.ws.Holder<java.lang.String> supportInfoUri,javax.xml.ws.Holder<java.lang.String> systemBackupUri,javax.xml.ws.Holder<org.onvif.ver10.device.wsdl.GetSystemUrisResponse.Extension> extension) { 
        LOG.info("Executing operation getSystemUris");
        try {
            org.onvif.ver10.schema.SystemLogUriList systemLogUrisValue = null;
            systemLogUris.value = systemLogUrisValue;
            java.lang.String supportInfoUriValue = "";
            supportInfoUri.value = supportInfoUriValue;
            java.lang.String systemBackupUriValue = "";
            systemBackupUri.value = systemBackupUriValue;
            org.onvif.ver10.device.wsdl.GetSystemUrisResponse.Extension extensionValue = null;
            extension.value = extensionValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#startSystemRestore(java.lang.String  uploadUri ,)javax.xml.datatype.Duration  expectedDownTime )*
     */
    public void startSystemRestore(javax.xml.ws.Holder<java.lang.String> uploadUri,javax.xml.ws.Holder<javax.xml.datatype.Duration> expectedDownTime) { 
        LOG.info("Executing operation startSystemRestore");
        try {
            java.lang.String uploadUriValue = "";
            uploadUri.value = uploadUriValue;
            javax.xml.datatype.Duration expectedDownTimeValue = null;
            expectedDownTime.value = expectedDownTimeValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#createCertificate(java.lang.String  certificateID ,)java.lang.String  subject ,)javax.xml.datatype.XMLGregorianCalendar  validNotBefore ,)javax.xml.datatype.XMLGregorianCalendar  validNotAfter )*
     */
    public org.onvif.ver10.schema.Certificate createCertificate(java.lang.String certificateID,java.lang.String subject,javax.xml.datatype.XMLGregorianCalendar validNotBefore,javax.xml.datatype.XMLGregorianCalendar validNotAfter) { 
        LOG.info("Executing operation createCertificate");
        System.out.println(certificateID);
        System.out.println(subject);
        System.out.println(validNotBefore);
        System.out.println(validNotAfter);
        try {
            org.onvif.ver10.schema.Certificate _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#getHostname(*
     */
    public org.onvif.ver10.schema.HostnameInformation getHostname() { 
        LOG.info("Executing operation getHostname");
        try {
            org.onvif.ver10.schema.HostnameInformation _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#setRelayOutputState(java.lang.String  relayOutputToken ,)org.onvif.ver10.schema.RelayLogicalState  logicalState )*
     */
    public void setRelayOutputState(java.lang.String relayOutputToken,org.onvif.ver10.schema.RelayLogicalState logicalState) { 
        LOG.info("Executing operation setRelayOutputState");
        System.out.println(relayOutputToken);
        System.out.println(logicalState);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#getSystemLog(org.onvif.ver10.schema.SystemLogType  logType )*
     */
    public org.onvif.ver10.schema.SystemLog getSystemLog(org.onvif.ver10.schema.SystemLogType logType) { 
        LOG.info("Executing operation getSystemLog");
        System.out.println(logType);
        try {
            org.onvif.ver10.schema.SystemLog _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#getCertificates(*
     */
    public java.util.List<org.onvif.ver10.schema.Certificate> getCertificates() { 
        LOG.info("Executing operation getCertificates");
        try {
            java.util.List<org.onvif.ver10.schema.Certificate> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#setDiscoveryMode(org.onvif.ver10.schema.DiscoveryMode  discoveryMode )*
     */
    public void setDiscoveryMode(org.onvif.ver10.schema.DiscoveryMode discoveryMode) { 
        LOG.info("Executing operation setDiscoveryMode");
        System.out.println(discoveryMode);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#setDynamicDNS(org.onvif.ver10.schema.DynamicDNSType  type ,)java.lang.String  name ,)javax.xml.datatype.Duration  ttl )*
     */
    public void setDynamicDNS(org.onvif.ver10.schema.DynamicDNSType type,java.lang.String name,javax.xml.datatype.Duration ttl) { 
        LOG.info("Executing operation setDynamicDNS");
        System.out.println(type);
        System.out.println(name);
        System.out.println(ttl);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#getRemoteDiscoveryMode(*
     */
    public org.onvif.ver10.schema.DiscoveryMode getRemoteDiscoveryMode() { 
        LOG.info("Executing operation getRemoteDiscoveryMode");
        try {
            org.onvif.ver10.schema.DiscoveryMode _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#getDNS(*
     */
    public org.onvif.ver10.schema.DNSInformation getDNS() { 
        LOG.info("Executing operation getDNS");
        try {
            org.onvif.ver10.schema.DNSInformation _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#loadCertificates(java.util.List<org.onvif.ver10.schema.Certificate>  nvtCertificate )*
     */
    public void loadCertificates(java.util.List<org.onvif.ver10.schema.Certificate> nvtCertificate) { 
        LOG.info("Executing operation loadCertificates");
        System.out.println(nvtCertificate);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#setUser(java.util.List<org.onvif.ver10.schema.User>  user )*
     */
    public void setUser(java.util.List<org.onvif.ver10.schema.User> user) { 
        LOG.info("Executing operation setUser");
        System.out.println(user);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#setNTP(boolean  fromDHCP ,)java.util.List<org.onvif.ver10.schema.NetworkHost>  ntpManual )*
     */
    public void setNTP(boolean fromDHCP,java.util.List<org.onvif.ver10.schema.NetworkHost> ntpManual) { 
        LOG.info("Executing operation setNTP");
        System.out.println(fromDHCP);
        System.out.println(ntpManual);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#startFirmwareUpgrade(java.lang.String  uploadUri ,)javax.xml.datatype.Duration  uploadDelay ,)javax.xml.datatype.Duration  expectedDownTime )*
     */
    public void startFirmwareUpgrade(javax.xml.ws.Holder<java.lang.String> uploadUri,javax.xml.ws.Holder<javax.xml.datatype.Duration> uploadDelay,javax.xml.ws.Holder<javax.xml.datatype.Duration> expectedDownTime) { 
        LOG.info("Executing operation startFirmwareUpgrade");
        try {
            java.lang.String uploadUriValue = "";
            uploadUri.value = uploadUriValue;
            javax.xml.datatype.Duration uploadDelayValue = null;
            uploadDelay.value = uploadDelayValue;
            javax.xml.datatype.Duration expectedDownTimeValue = null;
            expectedDownTime.value = expectedDownTimeValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#getEndpointReference(org.onvif.ver10.device.wsdl.GetEndpointReference  parameters )*
     */
    public org.onvif.ver10.device.wsdl.GetEndpointReferenceResponse getEndpointReference(GetEndpointReference parameters) { 
        LOG.info("Executing operation getEndpointReference");
        System.out.println(parameters);
        try {
            org.onvif.ver10.device.wsdl.GetEndpointReferenceResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#setNetworkInterfaces(java.lang.String  interfaceToken ,)org.onvif.ver10.schema.NetworkInterfaceSetConfiguration  networkInterface )*
     */
    public boolean setNetworkInterfaces(java.lang.String interfaceToken,org.onvif.ver10.schema.NetworkInterfaceSetConfiguration networkInterface) { 
        LOG.info("Executing operation setNetworkInterfaces");
        System.out.println(interfaceToken);
        System.out.println(networkInterface);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#setHostnameFromDHCP(boolean  fromDHCP )*
     */
    public boolean setHostnameFromDHCP(boolean fromDHCP) { 
        LOG.info("Executing operation setHostnameFromDHCP");
        System.out.println(fromDHCP);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#setRemoteUser(org.onvif.ver10.schema.RemoteUser  remoteUser )*
     */
    public void setRemoteUser(org.onvif.ver10.schema.RemoteUser remoteUser) { 
        LOG.info("Executing operation setRemoteUser");
        System.out.println(remoteUser);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#addIPAddressFilter(org.onvif.ver10.schema.IPAddressFilter  ipAddressFilter )*
     */
    public void addIPAddressFilter(org.onvif.ver10.schema.IPAddressFilter ipAddressFilter) { 
        LOG.info("Executing operation addIPAddressFilter");
        System.out.println(ipAddressFilter);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#deleteUsers(java.util.List<java.lang.String>  username )*
     */
    public void deleteUsers(java.util.List<java.lang.String> username) { 
        LOG.info("Executing operation deleteUsers");
        System.out.println(username);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#getCertificateInformation(java.lang.String  certificateID )*
     */
    public org.onvif.ver10.schema.CertificateInformation getCertificateInformation(java.lang.String certificateID) { 
        LOG.info("Executing operation getCertificateInformation");
        System.out.println(certificateID);
        try {
            org.onvif.ver10.schema.CertificateInformation _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#getWsdlUrl(*
     */
    public java.lang.String getWsdlUrl() { 
        LOG.info("Executing operation getWsdlUrl");
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#getStorageConfiguration(java.lang.String  token )*
     */
    public org.onvif.ver10.device.wsdl.StorageConfiguration getStorageConfiguration(java.lang.String token) { 
        LOG.info("Executing operation getStorageConfiguration");
        System.out.println(token);
        try {
            org.onvif.ver10.device.wsdl.StorageConfiguration _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#getRelayOutputs(*
     */
    public java.util.List<org.onvif.ver10.schema.RelayOutput> getRelayOutputs() { 
        LOG.info("Executing operation getRelayOutputs");
        try {
            java.util.List<org.onvif.ver10.schema.RelayOutput> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#getDiscoveryMode(*
     */
    public org.onvif.ver10.schema.DiscoveryMode getDiscoveryMode() { 
        LOG.info("Executing operation getDiscoveryMode");
        try {
            org.onvif.ver10.schema.DiscoveryMode _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#setDot1XConfiguration(org.onvif.ver10.schema.Dot1XConfiguration  dot1XConfiguration )*
     */
    public void setDot1XConfiguration(org.onvif.ver10.schema.Dot1XConfiguration dot1XConfiguration) { 
        LOG.info("Executing operation setDot1XConfiguration");
        System.out.println(dot1XConfiguration);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#getServiceCapabilities(*
     */
    public org.onvif.ver10.device.wsdl.DeviceServiceCapabilities getServiceCapabilities() { 
        LOG.info("Executing operation getServiceCapabilities");
        try {
            org.onvif.ver10.device.wsdl.DeviceServiceCapabilities _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#setSystemDateAndTime(org.onvif.ver10.schema.SetDateTimeType  dateTimeType ,)boolean  daylightSavings ,)org.onvif.ver10.schema.TimeZone  timeZone ,)org.onvif.ver10.schema.DateTime  utcDateTime )*
     */
    public void setSystemDateAndTime(org.onvif.ver10.schema.SetDateTimeType dateTimeType,boolean daylightSavings,org.onvif.ver10.schema.TimeZone timeZone,org.onvif.ver10.schema.DateTime utcDateTime) { 
        LOG.info("Executing operation setSystemDateAndTime");
        System.out.println(dateTimeType);
        System.out.println(daylightSavings);
        System.out.println(timeZone);
        System.out.println(utcDateTime);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#setAccessPolicy(org.onvif.ver10.schema.BinaryData  policyFile )*
     */
    public void setAccessPolicy(org.onvif.ver10.schema.BinaryData policyFile) { 
        LOG.info("Executing operation setAccessPolicy");
        System.out.println(policyFile);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#getSystemSupportInformation(*
     */
    public org.onvif.ver10.schema.SupportInformation getSystemSupportInformation() { 
        LOG.info("Executing operation getSystemSupportInformation");
        try {
            org.onvif.ver10.schema.SupportInformation _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#setScopes(java.util.List<java.lang.String>  scopes )*
     */
    public void setScopes(java.util.List<java.lang.String> scopes) { 
        LOG.info("Executing operation setScopes");
        System.out.println(scopes);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#getDot1XConfiguration(java.lang.String  dot1XConfigurationToken )*
     */
    public org.onvif.ver10.schema.Dot1XConfiguration getDot1XConfiguration(java.lang.String dot1XConfigurationToken) { 
        LOG.info("Executing operation getDot1XConfiguration");
        System.out.println(dot1XConfigurationToken);
        try {
            org.onvif.ver10.schema.Dot1XConfiguration _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#getSystemBackup(*
     */
    public java.util.List<org.onvif.ver10.schema.BackupFile> getSystemBackup() { 
        LOG.info("Executing operation getSystemBackup");
        try {
            java.util.List<org.onvif.ver10.schema.BackupFile> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#getNetworkInterfaces(*
     */
    public java.util.List<org.onvif.ver10.schema.NetworkInterface> getNetworkInterfaces() { 
        LOG.info("Executing operation getNetworkInterfaces");
        try {
            java.util.List<org.onvif.ver10.schema.NetworkInterface> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#deleteDot1XConfiguration(java.util.List<java.lang.String>  dot1XConfigurationToken )*
     */
    public void deleteDot1XConfiguration(java.util.List<java.lang.String> dot1XConfigurationToken) { 
        LOG.info("Executing operation deleteDot1XConfiguration");
        System.out.println(dot1XConfigurationToken);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#getAccessPolicy(*
     */
    public org.onvif.ver10.schema.BinaryData getAccessPolicy() { 
        LOG.info("Executing operation getAccessPolicy");
        try {
            org.onvif.ver10.schema.BinaryData _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#setCertificatesStatus(java.util.List<org.onvif.ver10.schema.CertificateStatus>  certificateStatus )*
     */
    public void setCertificatesStatus(java.util.List<org.onvif.ver10.schema.CertificateStatus> certificateStatus) { 
        LOG.info("Executing operation setCertificatesStatus");
        System.out.println(certificateStatus);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#getDPAddresses(*
     */
    public java.util.List<org.onvif.ver10.schema.NetworkHost> getDPAddresses() { 
        LOG.info("Executing operation getDPAddresses");
        try {
            java.util.List<org.onvif.ver10.schema.NetworkHost> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#getZeroConfiguration(*
     */
    public org.onvif.ver10.schema.NetworkZeroConfiguration getZeroConfiguration() { 
        LOG.info("Executing operation getZeroConfiguration");
        try {
            org.onvif.ver10.schema.NetworkZeroConfiguration _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#createUsers(java.util.List<org.onvif.ver10.schema.User>  user )*
     */
    public void createUsers(java.util.List<org.onvif.ver10.schema.User> user) { 
        LOG.info("Executing operation createUsers");
        System.out.println(user);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#addScopes(java.util.List<java.lang.String>  scopeItem )*
     */
    public void addScopes(java.util.List<java.lang.String> scopeItem) { 
        LOG.info("Executing operation addScopes");
        System.out.println(scopeItem);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#systemReboot(*
     */
    public java.lang.String systemReboot() { 
        LOG.info("Executing operation systemReboot");
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#getDeviceInformation(java.lang.String  manufacturer ,)java.lang.String  model ,)java.lang.String  firmwareVersion ,)java.lang.String  serialNumber ,)java.lang.String  hardwareId )*
     */
    public void getDeviceInformation(javax.xml.ws.Holder<java.lang.String> manufacturer,javax.xml.ws.Holder<java.lang.String> model,javax.xml.ws.Holder<java.lang.String> firmwareVersion,javax.xml.ws.Holder<java.lang.String> serialNumber,javax.xml.ws.Holder<java.lang.String> hardwareId) { 
        LOG.info("Executing operation getDeviceInformation");
        try {
            java.lang.String manufacturerValue = "";
            manufacturer.value = manufacturerValue;
            java.lang.String modelValue = "";
            model.value = modelValue;
            java.lang.String firmwareVersionValue = "";
            firmwareVersion.value = firmwareVersionValue;
            java.lang.String serialNumberValue = "";
            serialNumber.value = serialNumberValue;
            java.lang.String hardwareIdValue = "";
            hardwareId.value = hardwareIdValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#getRemoteUser(*
     */
    public org.onvif.ver10.schema.RemoteUser getRemoteUser() { 
        LOG.info("Executing operation getRemoteUser");
        try {
            org.onvif.ver10.schema.RemoteUser _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#createDot1XConfiguration(org.onvif.ver10.schema.Dot1XConfiguration  dot1XConfiguration )*
     */
    public void createDot1XConfiguration(org.onvif.ver10.schema.Dot1XConfiguration dot1XConfiguration) { 
        LOG.info("Executing operation createDot1XConfiguration");
        System.out.println(dot1XConfiguration);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#loadCACertificates(java.util.List<org.onvif.ver10.schema.Certificate>  caCertificate )*
     */
    public void loadCACertificates(java.util.List<org.onvif.ver10.schema.Certificate> caCertificate) { 
        LOG.info("Executing operation loadCACertificates");
        System.out.println(caCertificate);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#setHostname(java.lang.String  name )*
     */
    public void setHostname(java.lang.String name) { 
        LOG.info("Executing operation setHostname");
        System.out.println(name);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#removeIPAddressFilter(org.onvif.ver10.schema.IPAddressFilter  ipAddressFilter )*
     */
    public void removeIPAddressFilter(org.onvif.ver10.schema.IPAddressFilter ipAddressFilter) { 
        LOG.info("Executing operation removeIPAddressFilter");
        System.out.println(ipAddressFilter);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#getUsers(*
     */
    public java.util.List<org.onvif.ver10.schema.User> getUsers() { 
        LOG.info("Executing operation getUsers");
        try {
            java.util.List<org.onvif.ver10.schema.User> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#getStorageConfigurations(*
     */
    public java.util.List<org.onvif.ver10.device.wsdl.StorageConfiguration> getStorageConfigurations() { 
        LOG.info("Executing operation getStorageConfigurations");
        try {
            java.util.List<org.onvif.ver10.device.wsdl.StorageConfiguration> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#setRemoteDiscoveryMode(org.onvif.ver10.schema.DiscoveryMode  remoteDiscoveryMode )*
     */
    public void setRemoteDiscoveryMode(org.onvif.ver10.schema.DiscoveryMode remoteDiscoveryMode) { 
        LOG.info("Executing operation setRemoteDiscoveryMode");
        System.out.println(remoteDiscoveryMode);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#getNetworkProtocols(*
     */
    public java.util.List<org.onvif.ver10.schema.NetworkProtocol> getNetworkProtocols() { 
        LOG.info("Executing operation getNetworkProtocols");
        try {
            java.util.List<org.onvif.ver10.schema.NetworkProtocol> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#getScopes(*
     */
    public java.util.List<org.onvif.ver10.schema.Scope> getScopes() { 
        LOG.info("Executing operation getScopes");
        try {
            java.util.List<org.onvif.ver10.schema.Scope> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#loadCertificateWithPrivateKey(java.util.List<org.onvif.ver10.schema.CertificateWithPrivateKey>  certificateWithPrivateKey )*
     */
    public void loadCertificateWithPrivateKey(java.util.List<org.onvif.ver10.schema.CertificateWithPrivateKey> certificateWithPrivateKey) { 
        LOG.info("Executing operation loadCertificateWithPrivateKey");
        System.out.println(certificateWithPrivateKey);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#upgradeSystemFirmware(org.onvif.ver10.schema.AttachmentData  firmware )*
     */
    public java.lang.String upgradeSystemFirmware(org.onvif.ver10.schema.AttachmentData firmware) { 
        LOG.info("Executing operation upgradeSystemFirmware");
        System.out.println(firmware);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#getDot11Status(java.lang.String  interfaceToken )*
     */
    public org.onvif.ver10.schema.Dot11Status getDot11Status(java.lang.String interfaceToken) { 
        LOG.info("Executing operation getDot11Status");
        System.out.println(interfaceToken);
        try {
            org.onvif.ver10.schema.Dot11Status _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#getPkcs10Request(java.lang.String  certificateID ,)java.lang.String  subject ,)org.onvif.ver10.schema.BinaryData  attributes )*
     */
    public org.onvif.ver10.schema.BinaryData getPkcs10Request(java.lang.String certificateID,java.lang.String subject,org.onvif.ver10.schema.BinaryData attributes) { 
        LOG.info("Executing operation getPkcs10Request");
        System.out.println(certificateID);
        System.out.println(subject);
        System.out.println(attributes);
        try {
            org.onvif.ver10.schema.BinaryData _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#getDot1XConfigurations(*
     */
    public java.util.List<org.onvif.ver10.schema.Dot1XConfiguration> getDot1XConfigurations() { 
        LOG.info("Executing operation getDot1XConfigurations");
        try {
            java.util.List<org.onvif.ver10.schema.Dot1XConfiguration> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.onvif.ver10.device.wsdl.Device#restoreSystem(java.util.List<org.onvif.ver10.schema.BackupFile>  backupFiles )*
     */
    public void restoreSystem(java.util.List<org.onvif.ver10.schema.BackupFile> backupFiles) { 
        LOG.info("Executing operation restoreSystem");
        System.out.println(backupFiles);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
