package org.onvif.ver10.device.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * DeviceService service = new DeviceService();
 * Device portType = service.getDevicePort();
 * portType.getServices(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "DeviceService", targetNamespace = "http://www.onvif.org/ver10/device/wsdl", wsdlLocation = "file:/D:/OPENCVR/javaonvif/wsdls/devicemgmt_1.wsdl")
public class DeviceService extends Service {

	private final static URL DEVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(org.onvif.ver10.device.wsdl.DeviceService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = org.onvif.ver10.device.wsdl.DeviceService.class
					.getResource(".");
			url = new URL(baseUrl,
					"file:/D:/OPENCVR/javaonvif/wsdls/devicemgmt_1.wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'file:/D:/OPENCVR/javaonvif/wsdls/devicemgmt_1.wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		DEVICESERVICE_WSDL_LOCATION = url;
	}

	public DeviceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public DeviceService() {
		super(DEVICESERVICE_WSDL_LOCATION, new QName(
				"http://www.onvif.org/ver10/device/wsdl", "DeviceService"));
	}

	/**
	 * 
	 * @return returns Device
	 */
	@WebEndpoint(name = "DevicePort")
	public Device getDevicePort() {
		return super.getPort(new QName(
				"http://www.onvif.org/ver10/device/wsdl", "DevicePort"),
				Device.class);
	}

}
